TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#

LIBRARY_IOC += SmarPod

INC += SmarPod.hpp

LIB_SRCS += SmarPod.cpp

DBD += SmarPodSupport.dbd


# #=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE